In [1]:
import time
import gym
import random
from IPython.display import clear_output
import numpy as np

In [2]:
env = gym.make("FrozenLake-v0")

In [3]:
action_column_size = env.action_space.n
observation_column_size = env.observation_space.n

q_table = np.zeros((observation_column_size, action_column_size))

In [4]:
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
num_ep = 10000
num_step = 100

discount_rate = 0.99
learning_rate = 0.1

exploration_rate = 1
max_exp_rate = 1
min_exp_rate = 0.01
exp_rate_decay = 0.01
